---
title: "Primer TP DMEyF"
date: "`r format(Sys.time(), '%d de %B del %Y')`"
#runtime: shiny
output:
  word_document: 
    fig_caption: yes
    #reference_doc: referword-doc.docx
    #toc: yes
  pdf_document:
    fig_caption: yes
    fig_crop: no
    number_sections: yes
    #toc: yes
  html_document:
    df_print: paged
    #toc: yes
header-includes: \usepackage[spanish]{babel}
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Educacion/Maestria_DM/2021_2C/DMEF")
#set wd para chunks
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)

knitr::opts_chunk$set(fig.width = 9)
knitr::opts_chunk$set(fig.height = 9)
knitr::opts_chunk$set(fig.align = "center")

library(compareGroups)
library(pander)
library(tidyverse)
library(kableExtra)
library(table1)
library(ggplot2)
library(GGally)
library(ggpubr)
require("data.table")
library("rpart")

```


```{r}
dtrain  <- fread("./datasetsOri/paquete_premium_202009.csv")

```
## basic eda
```{r}
basic_eda <- function(data)
{
status(data)
freq(data)
profiling_num(data)
plot_num(data)
describe(data)
}

library(tidyverse)
library(funModeling)
library(Hmisc)
```

## codebook
```{r codebook,eval=FALSE,message=F, warning=F}
library(dataMaid)
makeCodebook(dtrain)
```


# Modelo original profesores

```{r}
modelo  <- rpart("clase_ternaria ~ .",
                 data = dtrain,
                 xval=0,
                 cp=        -0.3, 
                 minsplit=  80,
                 minbucket=  1,
                 maxdepth=   8 )
```

## Aplico al modelo a los datos de 202011

```{r}
#cargo los datos de 202011, que es donde voy a APLICAR el modelo

dapply  <- fread("./datasetsOri/paquete_premium_202011.csv")

prediccion  <- predict( modelo, dapply , type = "prob") #aplico el modelo

```

```{r}
#prediccion es una matriz con TRES columnas, llamadas "BAJA+1", "BAJA+2"  y "CONTINUA"
#cada columna es el vector de probabilidades 

dapply[ , prob_baja2 := prediccion[, "BAJA+2"] ]
dapply[ , Predicted  := as.numeric(prob_baja2 > 0.025) ]

entrega  <- dapply[   , list(numero_de_cliente, Predicted) ] #genero la salida

#genero el archivo para Kaggle
fwrite( entrega, file="./kaggle/K101_001.csv", sep="," )
```

# Modelos míos

